name: my-first-actions
run-name: ${{github.actor}} is learning Github Actions
# 设置actions执行时机，此处为master分支pull时触发
on: 
  workflow_dispatch:
    inputs:
      options-1:
        description: "测试选项一"
        required: true
        default: "白天"
        type: choice
        options:
        - 白天
        - 黑夜
      options-2:
        description: "测试选项二"
        required: false
        type: choice
        options:
        - 太阳
        - 月亮
      environment:
        description: "环境选项"
        type: environment
        required: false

# action的job
jobs:
  # 一个jobs任务，名称为build
  check-bats-version:
    # 运行基础环境，设置为ubuntu
    runs-on: ubuntu-latest
    # jobs任务的步骤
    steps: 
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Print inputs
        run: |
          echo "测试选项一: $OPTIONS1"
          echo "测试选项二: $OPTIONS2"
          echo "environment: $ENVIRONMENT"
        env:
          OPTIONS1: ${{inputs.options-1}}
          OPTIONS2: ${{inputs.options-2}}
          ENVIRONMENT: ${{inputs.environment}}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: npm install
        run: npm install -g bats
      - name: npm install
        run: bats -v > output.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "测试文件名"
          path: "./output.txt"
  hello-world:
    runs-on: windows-latest
    steps:
      # 克隆仓库
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Compile and run some Code
        shell: cmd
        run: |
          cl.exe HelloWorld.cpp
          HelloWorld.exe
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "HelloWorld"
          path: "./HelloWorld.exe"

