name: my-first-actions
run-name: ${{github.actor}} is learning Github Actions
# 触发workflow事件
on:
# 设置actions执行时机，此处为master分支pull时触发
  pull:
    branches:
    - master
# action的job
jobs:
  # 一个jobs任务，名称为build
  check-bats-version:
    # 运行基础环境，设置为ubuntu
    runs-on: ubuntu-latest
    # jobs任务的步骤
    steps:
      - name: install
      run: npm install -g bats
      - name: run
      run: bats -v