name: my-first-actions
run-name: ${{github.actor}} is learning Github Actions
# 触发workflow事件
on: [push]
# 设置actions执行时机，此处为master分支pull时触发
# action的job
jobs:
  # 一个jobs任务，名称为build
  check-bats-version:
    # 运行基础环境，设置为ubuntu
    runs-on: ubuntu-latest
    # jobs任务的步骤
    steps: 
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: npm install
        run: npm install -g bats
      - name: npm install
        run: bats -v
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2